openapi: 3.1.0
info:
  title: Dictionary API
  version: 0.0.3
  description: <b>A clean architecture OOP TDD Rust API project &#x1F609;</b>
servers:
  - url: http://127.0.0.1
    description: Localhost
paths:
  /words:
    get:
      tags:
        - Available English words
      summary: See a list of all available English words
      description: "Currently, only 3 test words exist: a, ability, able."
      operationId: AllWords
      responses:
        '200':
          description: A list of words.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  a
                  ability
                  able
                  \u{1F60E}
        '404':
          description: No words found.
          content:
            text/plain:
              schema:
                type: string
                example: Words not exist yet \u{1F622}
    post:
      tags:
        - A new word
      summary: Add a new word
      requestBody:
        description: Field values are separated with new line.
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                newword
                3000
                новое слово
      description: Currently, words are put in memory only.
      operationId: AddWord
      responses:
        '201':
          description: The word was created successfully.
          content:
            text/plain:
              schema:
                type: string
                example: Word \"newword\" is added \u{1F60E}
        '400':
          description: Bad request.
          content:
            text/plain:
              schema:
                type: string
                example: Bad request \u{1F622}
    put:
      tags:
        - An updated word
      summary: Update a word
      requestBody:
        description: Field values are separated with new line.
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                updatedword
                5000
                новоеслово
      description: Currently, words are put in memory only.
      operationId: UpdateWord
      responses:
        '204':
          description: The word was updated successfully
        '404':
          description: The word is not found.
          content:
            text/plain:
              schema:
                type: string
                example: Word \"theword\" is not found \u{1F622}
  /words/{word}:
    get:
      tags:
        - English word translation
      summary: Get a translation of an English word
      description: "Currently, only 3 test words exist: a, ability, able."
      operationId: WordTranslation
      responses:
        '200':
          description: The word.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ability
                  1000
                  способность \u{1F60E}
        '404':
          description: The word is not found.
          content:
            text/plain:
              schema:
                type: string
                example: Word "qazxsw" is not found \u{1F622}
      parameters:
        - name: word
          in: path
          required: true
          description: An English word to translate.
          schema:
            type: string
tags:
  - name: English word translation
    description: Translate a word
  - name: Available English words
    description: Get a list of all words
  - name: A new word
    description: Add a new English word
  - name: An updated word
    description: Update an English word
