openapi: 3.1.0
info:
  title: Dictionary API
  version: 0.0.4
  description: <b>A clean architecture OOP TDD Rust API project &#x1F609;</b>
servers:
  - url: http://127.0.0.1
    description: Localhost
paths:
  /words:
    get:
      tags:
        - English words
      summary: See a list of all available English words
      description: "Currently, only 3 test words exist: testworda, testwordb, testworc."
      operationId: AllWords
      responses:
        '200':
          description: A list of words.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  testworda
                  testwordb
                  testwordc \u{1F60E}
        '404':
          description: No words found.
          content:
            text/plain:
              schema:
                type: string
                example: No words yet \u{1F622}
    post:
      tags:
        - A new word
      summary: Add a word
      requestBody:
        description: Field values are separated with new line.
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                newword
                5000
                новое слово

      description: Currently, words are put in memory only.
      operationId: AddWord
      responses:
        '201':
          description: The word was created successfully.
          content:
            text/plain:
              schema:
                type: string
                example: Word \"newword\" is added \u{1F60E}
        '400':
          description: Bad request.
          content:
            text/plain:
              schema:
                type: string
                example: Bad request \u{1F622}
    put:
      tags:
        - An updated word
      summary: Update a word
      requestBody:
        description: Field values are separated with new line.
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                newword
                7000
                новоеслово

      description: Currently, words are put in memory only.
      operationId: UpdateWord
      responses:
        '204':
          description: The word was updated successfully
        '404':
          description: The word is not found.
          content:
            text/plain:
              schema:
                type: string
                example: Word \"notexistant\" is not found \u{1F622}
  /words/{word}:
    get:
      tags:
        - An English word
      summary: Get a translation of an English word
      description: "Currently, only 3 test words exist: testworda, testwordb, testworc."
      operationId: GetWord
      responses:
        '200':
          description: The word.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  testworda
                  1000
                  лебедь \u{1F60E}
        '404':
          description: The word is not found.
          content:
            text/plain:
              schema:
                type: string
                example: Word "notexistant" is not found \u{1F622}
      parameters:
        - name: word
          in: path
          required: true
          description: An English word to translate.
          schema:
            type: string
    delete:
      tags:
        - A deleted word
      summary: Delete a word
      description: "Currently, only 3 test words exist: testworda, testwordb, testworc."
      operationId: DeleteWord
      responses:
        '204':
          description: The word was deleted successfully.
        '404':
          description: The word is not found.
          content:
            text/plain:
              schema:
                type: string
                example: Word "notexistant" is not found \u{1F622}
      parameters:
        - name: word
          in: path
          required: true
          description: An English word to delete.
          schema:
            type: string
tags:
  - name: An English word
    description: Translate a word
  - name: English words
    description: Get a list of all words
  - name: A new word
    description: Add an English word
  - name: An updated word
    description: Update an English word
  - name: A deleted word
    description: Delete an English word
